title: Scientific Foundation Models
navtitle: Scientific Foundation Models
description: |

# disabled because we are using a custom domain
#baseurl: /business-frontpage
color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

plugins:
- jekyll-seo-tag
- jekyll-sitemap

news:
  front_page_limit: 5

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _projects

exclude:
  - .sass-cache

analytics:
  gtag: G-DGCRY7J6T8

# make pages for the _projects folder
collections:
  projects:
    output: true
