title: Center for Scientific Foundation Models
navtitle: Center for Scientific Foundation Models
url: scifm.ai

plugins:
- jekyll-seo-tag
- jekyll-sitemap

news:
  front_page_limit: 2

sass:
  sass_dir: /assets/css/_sass
  style: compressed

exclude:
  - .sass-cache

analytics:
  gtag: G-DGCRY7J6T8

roles:
  - key: pi
    name: Principal Investigators
  - key: director
    name: Director
  - key: assoc_director
    name: Associate Directors
  - key: faculty
    name: Faculty
  - key: team
    name: Students  
  - key: postdoc
    name: Postdoctoral Scholars
  - key: colab
    name: Collaborators

organizations:
  - key: um
    name: University of Michigan
  - key: anl
    name: Argonne National Laboratory
  - key: lanl
    name: Los Almos National Laboratory
  - key: caltech
    name: California Institute of Technology
  - key: lbnl
    name: Lawrence Berkeley National Laboratory

# make pages for the _projects folder
collections:
  projects:
    output: true
