title: Scientific Foundation Models
navtitle: Scientific Foundation Models
description: |

plugins:
- jekyll-seo-tag
- jekyll-sitemap

news:
  front_page_limit: 5

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _projects

exclude:
  - .sass-cache

analytics:
  gtag: G-DGCRY7J6T8

roles:
  - key: pi
    name: Principle Investigators
  - key: team
    name: Core Team
  - key: colab
    name: Collaborators

# make pages for the _projects folder
collections:
  projects:
    output: true
